ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
      MAX_SCENE_REPEAT_EPISODES: 200
SIMULATOR:
  TURN_ANGLE: 10
  TILT_ANGLE: 10
  ACTION_SPACE_CONFIG: "v0"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True
  RGB_SENSOR:
    WIDTH: 64
    HEIGHT: 128
    HFOV: 90
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 64
    HEIGHT: 128
    HFOV: 90
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: Nav-v0
  POSSIBLE_ACTIONS: ["MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SUCCESS_DISTANCE: 1.0

  SENSORS: ['CUSTOM_VISTARGET_SENSOR',"PANORAMIC_SENSOR", "PANORAMIC_DEPTH_SENSOR"]
  GOAL_SENSOR_UUID: target_goal
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']

  DISTANCE_TO_GOAL:
    DISTANCE_TO: POINT


DATASET:
  TYPE: VisTargetNav-v1
  SPLIT: train
  DATA_PATH: "data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"
